import { useEffect, useRef, useState } from 'react'

import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import QRCode from 'qrcode'

import { ClipboardIcon } from '@heroicons/react/24/outline'

const copyToClipboard = (blob: Blob | null) => {
  if (!blob) throw new Error('blob is null')

  try {
    navigator.clipboard.write([new ClipboardItem({ 'image/png': blob })])
  } catch (error) {
    console.log(error)
  }
}

const Home: NextPage = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null)

  const [input, setInput] = useState<string>('')

  useEffect(() => {
    if (!canvasRef.current) return

    QRCode.toCanvas(canvasRef.current, input || 'https://gabrielluizep.dev', (error) => {
      if (error) console.error(error)
    })
  }, [input])

  return (
    <div>
      <Head>
        <title>QRCode Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center py-16">
        <h1 className="text-5xl font-extrabold text-transparent text-center bg-clip-text bg-gradient-to-r from-purple-500 via-blue-500 to-green-500 mb-8">
          QRCode Generator
        </h1>

        <div className="flex flex-col">
          <label htmlFor="input" className="text-xs font-mono">
            Insira aqui o texto
          </label>
          <input
            id="input"
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            className="mb-8"
          />
        </div>

        <div className="border border-slate-600 rounded-md w-64 aspect-square flex items-center justify-center p-8 text-center font-semibold relative">
          <div
            onClick={() => canvasRef?.current?.toBlob((b) => copyToClipboard(b))}
            className="group overflow-hidden absolute w-full h-full bg-black top-0 left-0 z-10 bg-opacity-0 hover:bg-opacity-60 transition-all duration-500 cursor-pointer active:bg-gradient-to-br active:from-blue-500 active:to-green-500"
          >
            <div className="absolute top-1/2 -translate-y-1/2 -left-48 group-hover:left-1/2 -translate-x-1/2 transition-all flex flex-col items-center justify-center">
              <ClipboardIcon className="h-12 w-12 text-white" />
              <p className="text-white font-bold whitespace-nowrap select-none">Copy to clipboard</p>
            </div>
          </div>
          <canvas ref={canvasRef} className="select-none" />
        </div>
      </main>
    </div>
  )
}

export default Home
